name: Acorn Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v2
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          acorn-version: main
      - name: Build
        run: |
          set -e
          acorn build .
          acorn run --profile test? .
